TOOLS:
  SELLWAND:
    name: "&eSellwand"
    lore:
    - "&dRight click to sell all items in the chest."
    material: DIAMOND_HOE
    multiplier: 1.5
  CRAFTWAND:
    name: "&eCraftwand"
    lore:
    - "&dRight click to craft all items in the chest."
    material: BLAZE_ROD
  TRENCHPICK:
    name: "&eTrench Pick"
    lore:
    - "&dMines all blocks in a 5x5 area."
    material: DIAMOND_PICKAXE
    enchantments:
    - DIG_SPEED,5
    - DURABILITY,3
  HARVESTERHOE:
    name: "&eHarvester Hoe"
    lore:
    - "&dAutomatically pick up all sugarcane."
    material: DIAMOND_HOE
  LIGHTNINGWAND:
    name: "&eLightning Wand"
    lore:
    - "&dRight click to summon a lightning bolt."
    material: GOLD_SWORD
    enchantments:
    - KNOCKBACK,2
    cooldown: 50000
  SANDWAND:
    name: "&eSand Wand"
    lore:
    - "&dRight click a sand pillar to remove it."
    material: DIAMOND_HOE
    cooldown: 50000

COOLDOWN_MESSAGE: "&cYou have &e%time% &cleft before you can use this again."

SELLABLEITEMS:
- IRON_INGOT,20.0
- GOLD_INGOT,100.0