TOOLS:
  Sellwand:
    name: "&eSellwand"
    lore:
    - "&dRight click to sell all items in the chest."
    material: DIAMOND_HOE
  Craftwand:
    name: "&eCraftwand"
    lore:
    - "&dRight click to craft all items in the chest."
    material: BLAZE_ROD