TOOLS:
  SELLWAND:
    name: "&3Sell Wand"
    lore:
    - "&7Right click on a collector to sell all"
    - "&7collections."
    material: DIAMOND_HOE
    multiplier: 1.5
  CRAFTWAND:
    name: "&eCraft Wand"
    lore:
    - "&dRight click to craft all items in the chest."
    material: BLAZE_ROD
  TRENCHPICK:
    name: "&eTrench Pick"
    lore:
    - "&dMines all blocks in a 5x5 area."
    material: DIAMOND_PICKAXE
    enchantments:
    - DIG_SPEED,5
    - DURABILITY,3
  HARVESTERHOE:
    name: "&aHarvester Hoe"
    lore:
    - "&7Automatically pick up all sugarcane."
    - ""
    - "&7&onote: &e&ocollectors = x2pickups"
    material: DIAMOND_HOE
  LIGHTNINGWAND:
    name: "&eLightning Wand"
    lore:
    - "&dRight click to summon a lightning bolt."
    material: GOLD_SWORD
    enchantments:
    - KNOCKBACK,2
    cooldown: 50000
  SANDWAND:
    name: "&eSand Wand"
    lore:
    - "&dRight click a sand pillar to remove it."
    material: DIAMOND_HOE
    cooldown: 50000
  TNTWAND:
    name: "&cTnt Wand"
    lore:
      - "&7Right click on a collector to withdraw"
      - "&7all tnt to your faction bank."
    material: DIAMOND_HOE

COOLDOWN_MESSAGE: "&cYou have &e%time% &cleft before you can use this again."

SELLABLEITEMS:
- IRON_INGOT,20.0
- GOLD_INGOT,100.0